=== RomanAlshevscky/task_2.Sax_Stax_Dom/2.1XSD_XML_DOM/menuScheme.xsd
<?xml version="1.0" encoding="utf-8"?>
    <schema targetNamespace="http://www.XML-XSD.com"
               xmlns:tns="http://www.XML-XSD.com"
               xmlns="http://www.w3.org/2001/XMLSchema"
               attributeFormDefault="unqualified"
               elementFormDefault="qualified" >


        <element name="restaurant" type="tns:Restaurant" />

        <complexType name="Restaurant">
            <sequence>
                <element name="menu" type="tns:Menu" />
            </sequence>
            <attribute name="name" type ="string" />
        </complexType>

        <complexType name="Menu">
            <all>
                <element name="section" type="tns:Section" />
            </all>
        </complexType>

        <complexType name="Section">
            <all>
                <element name ="dish" type="tns:Dish" />
            </all>
            <attribute name="name" type="string"/>
            <attribute name="id" type="ID" />
        </complexType>
    
        <complexType name="Dish">
            <sequence>
                <element name="photo" type="tns:Picture" />
                <element name="name" type="string" />
                <element name="desc" type="tns:Description" />
                <element name="portion" type="tns:Portion" />
                <element name="price" type="tns:Price" />
            </sequence>
        </complexType>

        <complexType name="Picture">
            <sequence>
                <element name="link" type="string" minOccurs="1" maxOccurs="1"/>
            </sequence>
        </complexType>

        <complexType name="Description">
            <all>
                <element name="desription" type="string" minOccurs="0" maxOccurs="1" /> 
            </all>
        </complexType>

        <complexType name="Portion">
            <choice>
                <element name="weigh" type="tns:Weight" minOccurs="1" />
                <element name="count" type="positiveInteger" minOccurs="1" maxOccurs="1" />
            </choice>
        </complexType>

        <complexType name="Weight">
            <all>
                <element name="value" type="positiveInteger" />
            </all>
            <attribute name="units" type="string" />
        </complexType>
    
        <complexType name="Price">
            <all>
                <element name="value" type="positiveInteger" minOccurs="0"/>
            </all>
            <attribute name="currency" type="string"/>
        </complexType>
    
    </schema>

=== RomanAlshevscky/task_2.Sax_Stax_Dom/2.3DomAnalyzer/JWD_Java3_1_1/JWD_Java3_1_1/menu.xml
<?xml version="1.0" encoding="utf-8"?>
            <restaurant xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xmlns="http://www.menu_schema.by"
                     xsi:schemaLocation="http://www.menu_schema.by menuScheme.xsd"
                     name="Жемчужина">
                <menu>
                    <section name = "Холодные закуски" >
                        <dish>
                            <photo />
                            <name>Фестиваль салатов</name>
                            <desc></desc>
                            <portion>
                                <weight>400/10</weight>
                            </portion>
                            <price />
                        </dish>

                        <dish>
                            <photo />
                            <name>Оливки, маслины</name>
                            <desc></desc>
                            <portion>
                                <weight>50</weight>
                            </portion>
                            <price />
                        </dish>

                    </section>

                       <section name = "Холодные закуски" >

                        <dish>
                            <photo />
                            <name>Оливки, маслины</name>
                            <desc></desc>
                            <portion>
                                <weight>50</weight>
                            </portion>
                            <price />
                        </dish>

                    </section>

                    <section name = "Салаты"  />
                    <section name = "Супы"  />
                
                </menu>
            </restaurant>
